### ISSUE TITLE
Feature: Menu Creation

### ISSUE THREAD

**Issue by tremainebuchanan** [slashroots/slashroots-website-v2#37] opened 2016-01-21 18:39 UTC
Currently, the keystone does not have the facility to dynamically generate menu or submenu items once a page is created. Ideally, a user should be able to create a menu/submenu and attach a page(s). The front end should fetch from the database this menu and display same.

**Comment by paradoxxjm** [comment] 2016-02-16 16:38
Duplicate of #22

**Closed as completed by paradoxxjm** 2016-02-16 16:38 UTC
Labels: duplicate, enhancement
